60 index selector non negative
V0ldek/rsonpath pull request #128
Opened 2023-04-28 04:57 UTC by zwerdlds

## Issue
This PR implements the non-negative index selector.

Resolves: #60 

## Checklist
- [x] I ran `just verify` locally and it succeeded.
- [x] Issue was given <span style="color: #FF4400">go ahead</span> and is linked above
- [x] Unit tests for my changes are included

2023-04-28 19:11 UTC, V0ldek requested changes
The error message for too large numbers is less than ideal:

![image](https://user-images.githubusercontent.com/20441980/235230401-49eeed5e-f0a1-406a-8c6a-2b02dcb93bf7.png)

Let's leave it as is, but I'll create an issue for improving the messages.

2023-04-28 19:11 UTC, V0ldek commented on crates/rsonpath-lib/src/query/parser.rs
> +        assert_eq!(result, Ok(("", 9007199254740991.try_into().unwrap())));
This is giving me a warning from clippy about long literals:

```suggestion
        assert_eq!(result, Ok(("", 9_007_199_254_740_991.try_into().unwrap())));
```

2023-04-28 21:34 UTC, zwerdlds commented on crates/rsonpath-lib/src/query.rs
> +    }
Agreed;  This seems to stem from my misunderstanding regarding the inclusivity described previously

2023-04-28 22:00 UTC, zwerdlds commented on crates/rsonpath-lib/src/query.rs
> +    }
I added some tests in query to validate the conversion at the bounds.

2023-04-28 22:01 UTC, zwerdlds commented on crates/rsonpath-lib/src/query/parser.rs
> +}
I've removed the incorrect selector.

2023-04-28 22:06 UTC, zwerdlds commented on crates/rsonpath-lib/src/query/parser.rs
> +            .ok_or(ArrayIndexError::UpperLimitLengthCalculationError)
I guess you're right that its pretty unlikely the bound will change, which is really the only reason this is here.  Plus if it does it should get caught in at least one test.  Changed per se.

2023-05-01 20:35 UTC, V0ldek approved these changes

2023-05-03 14:18 UTC, zwerdlds commented on crates/rsonpath-lib/src/query/parser.rs
> +        if cs.len() > (ARRAY_INDEX_ULIMIT_B10_DIGIT_CT + 1) {
I renamed it to ARRAY_INDEX_ULIMIT_BASE_10_DIGIT_COUNT

2023-05-03 15:27 UTC, zwerdlds commented
There was a minor change to an unexpected part of the system in f62de26c0f511a65ccbdd23f1514d7aff4c43ac6

2023-05-04 12:21 UTC, V0ldek approved these changes

2023-05-04 12:26 UTC, merged